apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - mongo.yaml
  - mariadb.yaml
  - ai.yaml
  - backend.yaml
  - frontend.yaml
  - monitoring.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    namespace: skinai
    files:
      - prometheus.yml=monitoring/prometheus.yml
  - name: grafana-datasource-config
    namespace: skinai
    files:
      - prometheus.yml=monitoring/grafana-datasource.yml
  - name: grafana-dashboard-provider
    namespace: skinai
    files:
      - skinai.yml=monitoring/grafana-dashboard-provider.yml
  - name: grafana-dashboards
    namespace: skinai
    files:
      - overview.json=monitoring/dashboards/overview.json
      - system.json=monitoring/dashboards/system.json
      - backend.json=monitoring/dashboards/backend.json
      - ai.json=monitoring/dashboards/ai.json
