apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: skinai
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      terminationGracePeriodSeconds: 45
      containers:
        - name: backend
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 15"]
