apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - storage-class.yaml
  - configmap.yaml
  - ../../redis.yaml
  - ../../mariadb.yaml
  - ../../ai.yaml
  - ../../backend.yaml
  - ../../frontend.yaml
  - ../../monitoring.yaml
  - pdb.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    namespace: skinai
    files:
      - prometheus.yml=../../monitoring/prometheus.yml
  - name: grafana-datasource-config
    namespace: skinai
    files:
      - prometheus.yml=../../monitoring/grafana-datasource.yml
  - name: grafana-dashboard-provider
    namespace: skinai
    files:
      - skinai.yml=../../monitoring/grafana-dashboard-provider.yml
  - name: grafana-dashboards
    namespace: skinai
    files:
      - system.json=../../monitoring/dashboards/system.json
      - backend.json=../../monitoring/dashboards/backend.json
      - ai.json=../../monitoring/dashboards/ai.json

patches:
  - path: frontend-deployment-patch.yaml
  - target:
      kind: Service
      name: frontend
    path: frontend-service-patch.yaml
  - path: backend-deployment-patch.yaml
  - target:
      kind: Deployment
      name: backend
    path: backend-probes-patch.yaml
  - path: ai-deployment-patch.yaml
  - target:
      kind: PersistentVolumeClaim
      name: ai-uploads
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: auto-ebs-sc
  - target:
      kind: PersistentVolumeClaim
      name: mariadb-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: auto-ebs-sc
  - target:
      kind: PersistentVolumeClaim
      name: redis-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: auto-ebs-sc
  - target:
      kind: PersistentVolumeClaim
      name: prometheus-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: auto-ebs-sc
  - target:
      kind: PersistentVolumeClaim
      name: grafana-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: auto-ebs-sc

images:
  - name: comprehensive-design-frontend
    newName: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/skinai-frontend
    newTag: latest
  - name: comprehensive-design-backend
    newName: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/skinai-backend
    newTag: latest
  - name: comprehensive-design-ai
    newName: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/skinai-ai
    newTag: latest
